"""
Shared LLM Client for Maritime Guardian.
Provides a simple, centralized function to send prompts to Google Gemini.
"""

import os
from dotenv import load_dotenv
import google.generativeai as genai

# Load environment variables from .env file
load_dotenv()


def ask_ai(prompt: str) -> str:
    """
    Sends a prompt to Google Gemini and returns the plain text response.

    Parameters:
        prompt (str): The instructions or question to send to Gemini.

    Returns:
        str: The AI model's text response.
    """
    api_key = os.getenv("GEMINI_API_KEY")

    # If no API key is provided, return a clear fallback message
    # so teammates can still test their pipelines without crashing
    if not api_key:
        return (
            "[Fallback: GEMINI_API_KEY not found in .env] "
            "Vessel stopped transmitting AIS signals, representing a potential dark activity risk."
        )

    try:
        # Configure the Gemini client with the API key
        genai.configure(api_key=api_key)

        # Using gemini-1.5-flash for fast, reliable responses
        model = genai.GenerativeModel("gemini-1.5-flash")
        response = model.generate_content(prompt)

        # Return the clean text response
        if response and response.text:
            return response.text.strip()
        return "No response generated by the AI model."

    except Exception as e:
        # Graceful fallback in case of network issues, quota limits, or invalid keys
        return f"[Fallback due to AI error: {e}] Vessel flagged due to irregular AIS transmission gap."
